// Code generated by reset.gen. DO NOT EDIT.

package model

func (p *URL) Reset() {
	if p == nil {
		return
	}
	p.ShortURL = ""
	p.LongURL = ""
	p.UserUUID = ""
	p.IsDeleted = false
}

func (p *Request) Reset() {
	if p == nil {
		return
	}
	p.LongURL = ""
}

func (p *Response) Reset() {
	if p == nil {
		return
	}
	p.ShortURL = ""
}

func (p *BatchRequestItem) Reset() {
	if p == nil {
		return
	}
	p.Corr = ""
	p.LongURL = ""
}

func (p *BatchResponseItem) Reset() {
	if p == nil {
		return
	}
	p.Corr = ""
	p.ShortURL = ""
}
