// Package main — генерация метода Reset() для структур с меткой // generate:reset.
//
// Запуск:
//
//	go run ./cmd/reset
//
// Алгоритм:
//  1. Сканирует все пакеты начиная с корня.
//  2. Для каждой структуры с комментарием // generate:reset генерирует метод Reset().
//  3. Сохраняет в reset.gen.go в том же пакете.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

// FieldInfo содержит информацию о поле структуры.
type FieldInfo struct {
	Name string
	Type ast.Expr
}

// StructInfo содержит информацию о структуре для генерации Reset().
type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

const resetTemplate = `// Code generated by reset.gen. DO NOT EDIT.

package {{.Package}}
{{range .Structs}}
func (p *{{.Name}}) Reset() {
	if p == nil {
		return
	}
{{range .Fields}}	{{fieldReset "p." .Name .Type}}
{{end}}}
{{end}}`

func main() {
	fmt.Println("generating reset methods")
	if err := processPath("./..."); err != nil {
		fmt.Println("ошибка генерации:", err.Error())
		return
	}
	fmt.Println("файлы сгенерированы успешно")
}

// processPath сканирует пакеты и генерирует reset.gen.go для каждого пакета.
func processPath(path string) error {
	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedSyntax,
		Tests: false,
	}
	pkgs, err := packages.Load(cfg, path)
	if err != nil {
		return err
	}

	// Pass 1: collect all reset-struct names across all packages.
	knownStructs := make(map[string]bool)
	packageStructs := make(map[string][]StructInfo)

	for _, pkg := range pkgs {
		structs := scanPackage(pkg)
		if len(structs) > 0 {
			packageStructs[pkg.PkgPath] = structs
			for _, s := range structs {
				knownStructs[s.Name] = true
			}
		}
	}

	// Pass 2: generate reset.gen.go for each package with reset-structs.
	var resultErr error
	for _, pkg := range pkgs {
		structs, ok := packageStructs[pkg.PkgPath]
		if !ok || len(structs) == 0 {
			continue
		}
		dir := pkgDir(pkg)
		if dir == "" {
			continue
		}
		if err := generateFile(dir, pkg.Name, structs, knownStructs); err != nil {
			resultErr = errors.Join(resultErr, err)
		}
	}
	return resultErr
}

// scanPackage находит все структуры с // generate:reset в пакете.
func scanPackage(pkg *packages.Package) []StructInfo {
	var structs []StructInfo
	for _, file := range pkg.Syntax {
		if file == nil {
			continue
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if !hasResetComment(gen.Doc, ts.Doc) {
					continue
				}
				info := StructInfo{Name: ts.Name.Name}
				for _, field := range st.Fields.List {
					names := field.Names
					if len(names) == 0 {
						// Embedded field — derive name from type.
						if id, ok := field.Type.(*ast.Ident); ok {
							names = []*ast.Ident{{Name: id.Name}}
						} else if sel, ok := field.Type.(*ast.SelectorExpr); ok {
							names = []*ast.Ident{{Name: sel.Sel.Name}}
						}
					}
					for _, name := range names {
						info.Fields = append(info.Fields, FieldInfo{
							Name: name.Name,
							Type: field.Type,
						})
					}
				}
				structs = append(structs, info)
			}
		}
	}
	return structs
}

// hasResetComment проверяет наличие // generate:reset в комментариях.
func hasResetComment(docs ...*ast.CommentGroup) bool {
	for _, doc := range docs {
		if doc != nil && strings.Contains(doc.Text(), "generate:reset") {
			return true
		}
	}
	return false
}

// pkgDir возвращает директорию пакета по первому Go-файлу.
func pkgDir(pkg *packages.Package) string {
	if len(pkg.GoFiles) > 0 {
		return filepath.Dir(pkg.GoFiles[0])
	}
	return ""
}

// generateFile создаёт файл reset.gen.go по шаблону.
func generateFile(dir, pkgName string, structs []StructInfo, knownStructs map[string]bool) error {
	funcMap := template.FuncMap{
		"fieldReset": func(prefix, name string, expr ast.Expr) string {
			return fieldReset(prefix, name, expr, knownStructs)
		},
	}
	tmpl, err := template.New("reset").Funcs(funcMap).Parse(resetTemplate)
	if err != nil {
		return err
	}
	data := struct {
		Package string
		Structs []StructInfo
	}{
		Package: pkgName,
		Structs: structs,
	}
	var buf bytes.Buffer
	if err = tmpl.Execute(&buf, data); err != nil {
		return err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println("format error:", err.Error())
		formatted = buf.Bytes()
	}
	path := filepath.Join(dir, "reset.gen.go")
	if err := os.WriteFile(path, formatted, 0644); err != nil {
		return err
	}
	fmt.Println("generated:", path)
	return nil
}

// fieldReset генерирует код сброса поля к нулевому значению.
//
// Правила:
//   - примитивы → нулевые значения (0, "", false)
//   - слайсы → обрезка до длины 0 (s[:0])
//   - мапы → clear(m)
//   - указатели на примитивы → разыменование и присваивание нуля
//   - указатели на структуры с Reset() → вызов Reset()
//   - вложенные структуры с Reset() → вызов Reset()
//   - прочие типы → type assertion на interface{ Reset() }
func fieldReset(prefix, name string, expr ast.Expr, knownStructs map[string]bool) string {
	x := prefix + name
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return fmt.Sprintf(`%s = ""`, x)
		case "bool":
			return fmt.Sprintf(`%s = false`, x)
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "complex64", "complex128",
			"byte", "rune", "uintptr":
			return fmt.Sprintf(`%s = 0`, x)
		default:
			if knownStructs[t.Name] {
				return fmt.Sprintf(`%s.Reset()`, x)
			}
			return fmt.Sprintf(`if v, ok := (any)(%s).(interface{ Reset() }); ok && v != nil { v.Reset() }`, x)
		}
	case *ast.ArrayType:
		if t.Len == nil {
			return fmt.Sprintf(`%s = %s[:0]`, x, x)
		}
		return fmt.Sprintf(`for i := range %s { %s[i] = %s }`, x, x, zeroValue(t.Elt))
	case *ast.MapType:
		return fmt.Sprintf(`clear(%s)`, x)
	case *ast.StarExpr:
		switch inner := t.X.(type) {
		case *ast.Ident:
			switch inner.Name {
			case "string":
				return fmt.Sprintf(`if %s != nil { *%s = "" }`, x, x)
			case "bool":
				return fmt.Sprintf(`if %s != nil { *%s = false }`, x, x)
			case "int", "int8", "int16", "int32", "int64",
				"uint", "uint8", "uint16", "uint32", "uint64",
				"float32", "float64", "complex64", "complex128",
				"byte", "rune", "uintptr":
				return fmt.Sprintf(`if %s != nil { *%s = 0 }`, x, x)
			default:
				if knownStructs[inner.Name] {
					return fmt.Sprintf(`if %s != nil { %s.Reset() }`, x, x)
				}
				return fmt.Sprintf(`if %s != nil { if v, ok := (any)(%s).(interface{ Reset() }); ok && v != nil { v.Reset() } }`, x, x)
			}
		default:
			return fmt.Sprintf(`if %s != nil { if v, ok := (any)(%s).(interface{ Reset() }); ok && v != nil { v.Reset() } }`, x, x)
		}
	case *ast.SelectorExpr:
		return fmt.Sprintf(`if v, ok := (any)(%s).(interface{ Reset() }); ok && v != nil { v.Reset() }`, x)
	default:
		return ""
	}
}

// zeroValue возвращает строковое представление нулевого значения для типа.
func zeroValue(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return `""`
		case "bool":
			return `false`
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "byte", "rune", "uintptr":
			return `0`
		default:
			return t.Name + `{}`
		}
	case *ast.ArrayType, *ast.MapType, *ast.StarExpr:
		return `nil`
	default:
		return `nil`
	}
}
