// Package main — генерация метода Reset() для структур с меткой // generate:reset.
//
// Запуск:
//
//	go run ./cmd/reset
//
// Алгоритм:
//  1. Сканирует все пакеты начиная с корня.
//  2. Для каждой структуры с комментарием // generate:reset генерирует метод Reset().
//  3. Сохраняет в reset.gen.go в том же пакете.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/rs/zerolog/log"
	"golang.org/x/tools/go/packages"
)

// FieldInfo содержит информацию о поле структуры.
type FieldInfo struct {
	Name string
	Type ast.Expr
}

// StructInfo содержит информацию о структуре для генерации Reset().
type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

const resetTemplate = `// Code generated by reset.gen. DO NOT EDIT.

package {{.Package}}
{{range .Structs}}
func (p *{{.Name}}) Reset() {
	if p == nil {
		return
	}
{{range .Fields}}	{{fieldReset "p." .Name .Type}}
{{end}}}
{{end}}`

var zeroValues = map[string]string{
	"string":     `""`,
	"bool":       `false`,
	"int":        `0`,
	"int8":       `0`,
	"int16":      `0`,
	"int32":      `0`,
	"int64":      `0`,
	"uint":       `0`,
	"uint8":      `0`,
	"uint16":     `0`,
	"uint32":     `0`,
	"uint64":     `0`,
	"float32":    `0`,
	"float64":    `0`,
	"complex64":  `0`,
	"complex128": `0`,
	"byte":       `0`,
	"rune":       `0`,
	"uintptr":    `0`,
}

func main() {
	fmt.Println("generating reset methods")
	if err := processPath("./..."); err != nil {
		log.Fatal().Err(err).Msg("ошибка генерации")
	}
	fmt.Println("файлы сгенерированы успешно")
}

// processPath сканирует пакеты и генерирует reset.gen.go для каждого пакета.
func processPath(path string) error {
	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedSyntax,
		Tests: false,
	}
	pkgs, err := packages.Load(cfg, path)
	if err != nil {
		return err
	}

	knownStructs := make(map[string]bool)
	packageStructs := make(map[string][]StructInfo)

	for _, pkg := range pkgs {
		structs := scanPackage(pkg)
		if len(structs) > 0 {
			packageStructs[pkg.PkgPath] = structs
			for _, s := range structs {
				knownStructs[s.Name] = true
			}
		}
	}

	var resultErr error
	for _, pkg := range pkgs {
		structs, ok := packageStructs[pkg.PkgPath]
		if !ok || len(structs) == 0 {
			continue
		}
		dir := pkgDir(pkg)
		if dir == "" {
			continue
		}
		if err := generateFile(dir, pkg.Name, structs, knownStructs); err != nil {
			resultErr = errors.Join(resultErr, err)
		}
	}
	return resultErr
}

func scanPackage(pkg *packages.Package) []StructInfo {
	var structs []StructInfo
	for _, file := range pkg.Syntax {
		if file == nil {
			continue
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if !hasResetComment(gen.Doc, ts.Doc) {
					continue
				}
				info := StructInfo{Name: ts.Name.Name}
				for _, field := range st.Fields.List {
					names := field.Names
					if len(names) == 0 {
						// Embedded field — derive name from type.
						if id, ok := field.Type.(*ast.Ident); ok {
							names = []*ast.Ident{{Name: id.Name}}
						} else if sel, ok := field.Type.(*ast.SelectorExpr); ok {
							names = []*ast.Ident{{Name: sel.Sel.Name}}
						}
					}
					for _, name := range names {
						info.Fields = append(info.Fields, FieldInfo{
							Name: name.Name,
							Type: field.Type,
						})
					}
				}
				structs = append(structs, info)
			}
		}
	}
	return structs
}

// hasResetComment проверяет наличие // generate:reset в комментариях.
func hasResetComment(docs ...*ast.CommentGroup) bool {
	for _, doc := range docs {
		if doc != nil && strings.Contains(doc.Text(), "generate:reset") {
			return true
		}
	}
	return false
}

// pkgDir возвращает директорию пакета по первому Go-файлу.
func pkgDir(pkg *packages.Package) string {
	if len(pkg.GoFiles) > 0 {
		return filepath.Dir(pkg.GoFiles[0])
	}
	return ""
}

// generateFile создаёт файл reset.gen.go по шаблону.
func generateFile(dir, pkgName string, structs []StructInfo, knownStructs map[string]bool) error {
	funcMap := template.FuncMap{
		"fieldReset": func(prefix, name string, expr ast.Expr) string {
			return fieldReset(prefix, name, expr, knownStructs)
		},
	}
	tmpl, err := template.New("reset").Funcs(funcMap).Parse(resetTemplate)
	if err != nil {
		return err
	}
	data := struct {
		Package string
		Structs []StructInfo
	}{
		Package: pkgName,
		Structs: structs,
	}
	var buf bytes.Buffer
	if err = tmpl.Execute(&buf, data); err != nil {
		return err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println("format error:", err.Error())
		formatted = buf.Bytes()
	}
	path := filepath.Join(dir, "reset.gen.go")
	if err := os.WriteFile(path, formatted, 0644); err != nil {
		return err
	}
	fmt.Println("generated:", path)
	return nil
}

func tryReset(x string) string {
	return fmt.Sprintf(`if v, ok := (any)(%s).(interface{ Reset() }); ok && v != nil { v.Reset() }`, x)
}

func tryResetPtr(x string) string {
	return fmt.Sprintf(`if %s != nil { %s }`, x, tryReset(x))
}

// fieldReset генерирует код сброса поля к нулевому значению.
func fieldReset(prefix, name string, expr ast.Expr, knownStructs map[string]bool) string {
	x := prefix + name
	switch t := expr.(type) {
	case *ast.Ident:
		if zero, ok := zeroValues[t.Name]; ok {
			return fmt.Sprintf(`%s = %s`, x, zero)
		}
		if knownStructs[t.Name] {
			return fmt.Sprintf(`%s.Reset()`, x)
		}
		return tryReset(x)
	case *ast.ArrayType:
		if t.Len == nil {
			return fmt.Sprintf(`%s = %s[:0]`, x, x)
		}
		return fmt.Sprintf(`for i := range %s { %s[i] = %s }`, x, x, zeroValue(t.Elt))
	case *ast.MapType:
		return fmt.Sprintf(`clear(%s)`, x)
	case *ast.StarExpr:
		switch inner := t.X.(type) {
		case *ast.Ident:
			if zero, ok := zeroValues[inner.Name]; ok {
				return fmt.Sprintf(`if %s != nil { *%s = %s }`, x, x, zero)
			}
			if knownStructs[inner.Name] {
				return fmt.Sprintf(`if %s != nil { %s.Reset() }`, x, x)
			}
			return tryResetPtr(x)
		default:
			return tryResetPtr(x)
		}
	case *ast.SelectorExpr:
		return tryReset(x)
	default:
		return ""
	}
}

// zeroValue возвращает строковое представление нулевого значения для типа.
func zeroValue(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		if zero, ok := zeroValues[t.Name]; ok {
			return zero
		}
		return t.Name + `{}`
	case *ast.ArrayType, *ast.MapType, *ast.StarExpr:
		return `nil`
	default:
		return `nil`
	}
}
